<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118880" started-at="2017-11-30T16:04:14Z" finished-at="2017-11-30T16:06:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118880" started-at="2017-11-30T16:04:14Z" finished-at="2017-11-30T16:06:13Z">
      <class name="test.usuarios.Usuarios">
        <test-method status="PASS" signature="initializeTestBaseSetup()[pri:0, instance:test.usuarios.Usuarios@46d56d67]" name="initializeTestBaseSetup" is-config="true" duration-ms="26907" started-at="2017-11-30T11:04:14Z" finished-at="2017-11-30T11:04:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="FAIL" signature="crearUsuario()[pri:0, instance:test.usuarios.Usuarios@46d56d67]" name="crearUsuario" duration-ms="14065" started-at="2017-11-30T11:04:41Z" finished-at="2017-11-30T11:04:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ENRIQUE MARIN] but found [DANIEL FLORES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ENRIQUE MARIN] but found [DANIEL FLORES]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at test.usuarios.Usuarios.crearUsuario(Usuarios.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crearUsuario -->
        <test-method status="FAIL" signature="crearUsuarioIdRepetido()[pri:0, instance:test.usuarios.Usuarios@46d56d67]" name="crearUsuarioIdRepetido" duration-ms="69775" started-at="2017-11-30T11:04:55Z" finished-at="2017-11-30T11:06:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate element: //html/body/div[3]/div/div/div/form/div/div[2]/div/span
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'DESKTOP-LV7M220', ip: '192.168.1.163', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\WINDOW~1\AppData\Local\Temp\rust_mozprofile.51eRqBokGuKz, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0, platformVersion=10.0, moz:processID=11712, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 03a99dec-0dce-45be-ab5c-d61a8edf4c74
*** Element info: {Using=xpath, value=//html/body/div[3]/div/div/div/form/div/div[2]/div/span}]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate element: //html/body/div[3]/div/div/div/form/div/div[2]/div/span
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'DESKTOP-LV7M220', ip: '192.168.1.163', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\WINDOW~1\AppData\Local\Temp\rust_mozprofile.51eRqBokGuKz, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=54.0, platformVersion=10.0, moz:processID=11712, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 03a99dec-0dce-45be-ab5c-d61a8edf4c74
*** Element info: {Using=xpath, value=//html/body/div[3]/div/div/div/form/div/div[2]/div/span}
	at org.testng.Assert.fail(Assert.java:93)
	at test.usuarios.Usuarios.crearUsuarioIdRepetido(Usuarios.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crearUsuarioIdRepetido -->
        <test-method status="PASS" signature="crearUsuarionNikrepetido()[pri:0, instance:test.usuarios.Usuarios@46d56d67]" name="crearUsuarionNikrepetido" duration-ms="7771" started-at="2017-11-30T11:06:05Z" finished-at="2017-11-30T11:06:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crearUsuarionNikrepetido -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.usuarios.Usuarios@46d56d67]" name="tearDown" is-config="true" duration-ms="341" started-at="2017-11-30T11:06:13Z" finished-at="2017-11-30T11:06:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.usuarios.Usuarios -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
